AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false

SpaceBeforeFirstArg:
  Exclude:
    - "**/metadata.rb"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w':    '()'
    '%i':    '()'
    '%r':    '//'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/BlockLength:
  Max: 250
