sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

#branches:
#only:
#- master

services: docker

#env:
#matrix:
#- INSTANCE=default-centos-7
#- INSTANCE=default-centos-7 CHEF_VERSION=12.19.36

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(CHEF_LICENSE="accept" /opt/chefdk/bin/chef shell-init bash)" && CHEF_LICENSE="accept" chef gem install berkshelf --version '= 7.0.1'
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/chef gem search toml-rb
  - /opt/chefdk/embedded/bin/chef gem install toml-rb --version '= 1.1.1'

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

#matrix:
#allow_failures:
#- env: INSTANCE=default-centos-7
#include:
#- script:
#- /opt/chefdk/bin/chef exec rake
#env: UNIT_AND_LINT=1

jobs:
  include:
    - stage: unittest
      script: /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
    - stage: test-centos7-chef-12
      if: type = pull_request
      script: CHEF_VERSION=12.19.36 KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify default-centos-7
    - stage: test-centos7-chef-15
      if: type = pull_request
      script: CHEF_VERSION=15.2.20 KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify default-centos-7
    - stage: testdeploy
      if: type = pull_request
      script:
          - env
          - echo ${PWD}
          - uname -a
          - whoami
          - ./upload.sh
    - stage: deploy
      if: type = push
      name: "deploy to supermarket"
      script: ./upload.sh

stages:
  - unittest
  - test
  - testdeploy
  - deploy

