# Golang CircleCI 2.1 configuration file
version: 2.1

executors:
  centos7:
    docker:
      - image: centos:7
    working_directory: /mercury

commands:
  install_chefdk:
    description: Installs Chef Development Kit
    parameters:
      channel:
        description: ChefDK channel stable or current
        type: string
        default: stable
  steps:
      - run:
          name: Install Chef
          command: |
              curl -L https://omnitruck.chef.io/install.sh |
                    bash -s -- -c <<parameters.channel>> -P chefdk
              CHEF_LICENSE="accept" chef gem install berkshelf --version '= 7.0.8'
              chef gem install toml-rb --version '= 1.0.0'

jobs:
  test-centos7:
    executor: centos7
    steps:
      - checkout
      - install_chefdk:
          channel: stable

      - run: /opt/chefdk/embedded/bin/chef exec rake
      - run: berks
      - run: berks vendor ./cookbooks
      - run: chef-client --local-mode -z -o "recipe[mercury::default]"

workflows:
  version: 2

  build_test_package:
    jobs-centos7:
      - test
